## Information about the data

Q1: What are the observational units in the first data set \(the one you will use as the left\-hand one in the merge\)?\
A1: I'm using video game sales and video games critic scores datasets
Sales # Rank, Name, Platform, Year, Genre, Publisher, Sales per regions, other sales, Global sales

Q2: What are the observational units in the second data set \(the one you will use as the right\-hand one in the merge\)?\
A2: name, platform, release date, score, user score, developer, genre, players(some missing), # of critics, and metacritic users

Q3: What will the observational units be in the merged data set you expect to have as a result of this assignment?\
A3: sales vs review scores

Q4: Will you be doing a left, right, inner, or outer join?  Don't just state the answer in one word, but give a reason why your answer makes sense for the two data sets you have \(and possibly also your goals for the merge, if appropriate\)\.\
A4: I'm doing an inner merge where I merge the critic scores dataset into the sales dataset

Q5: How many rows and columns do you expect to have in the merged data set, and what is your reason for each of those numbers?\
A5: There will be less than 12k rows and 14 columns. Comparing the two datasets, the critics set has about 12k entries in it for reviewed games where the sales has over 16k. After running a match with all games in both sets, I will remove all other games from the sets so as to simplify the data, so at the most my merged set will have 12k rows. I'm using 14 columns so as to compare sales across regions, by total sales, genre, scores(both critics and users), # of critics, and # of players if applicable for popularity measures

Disclaimer, the data I'm using after cleaning is about 40% of the total entries. This is enough due to there being over 11000 unique entries that would take too many hours of manual checking to fix
Additionally, when trying to fuzzy match the entries that don't perfect match, the names of some games are matching, but often the numbers are not matching so sequels are being matched to prequels and vice versa
The data I'm using is not a fully random set, if you really want to make sure everything is perfect go through the datasets yourself be my guest. Console names, sequel numbers, and other game notations may make this a lot more complicated should you try to do this.

Importing necessary libraries

In [6]:
import pandas as pd
from difflib import get_close_matches

## Import both data sets

Creating the dataframes I will be merging after cleaning further down

In [7]:
# sales numbers in millions, review scores out of 10
sales = pd.read_csv("vgsales.csv")
reviews = pd.read_csv("games-data.csv")
# sales.head()
# reviews.head()

## Merge the two data sets

Looking for all directly matching game titles by name and adding them to a list for reference when merging

In [8]:
matches = sales.loc[sales["Name"].isin(reviews["name"]), "Name"].dropna().tolist()
count = len(matches)
print(count)
matches

8183

['Wii Sports',
 'Mario Kart Wii',
 'Wii Sports Resort',
 'Tetris',
 'New Super Mario Bros.',
 'Wii Play',
 'New Super Mario Bros. Wii',
 'Mario Kart DS',
 'Wii Fit',
 'Wii Fit Plus',
 'Kinect Adventures!',
 'Grand Theft Auto V',
 'Grand Theft Auto: San Andreas',
 'Grand Theft Auto V',
 'Grand Theft Auto: Vice City',
 'Brain Age 2: More Training in Minutes a Day',
 'Gran Turismo 3: A-Spec',
 'Call of Duty: Modern Warfare 3',
 'Call of Duty: Black Ops',
 'Call of Duty: Black Ops II',
 'Call of Duty: Black Ops II',
 'Call of Duty: Modern Warfare 2',
 'Call of Duty: Modern Warfare 3',
 'Grand Theft Auto III',
 'Super Smash Bros. Brawl',
 'Call of Duty: Black Ops',
 'Animal Crossing: Wild World',
 'Mario Kart 7',
 'Halo 3',
 'Grand Theft Auto V',
 'Super Mario 64',
 'Gran Turismo 4',
 'Super Mario Galaxy',
 'Grand Theft Auto IV',
 'Gran Turismo',
 'Super Mario 3D Land',
 'Gran Turismo 5',
 'Call of Duty: Modern Warfare 2',
 'Grand Theft Auto IV',
 'Super Mario 64',
 'Just Dance 3',
 'Call of Duty: Ghosts',
 'Halo: Reach',
 'Mario Kart 64',
 'New Super Mario Bros. 2',
 'Halo 4',
 'Final Fantasy VII',
 'Call of Duty: Ghosts',
 'Just Dance 2',
 'Gran Turismo 2',
 'Call of Duty 4: Modern Warfare',
 'Donkey Kong Country',
 'Minecraft',
 'Animal Crossing: New Leaf',
 'Mario Party DS',
 'The Elder Scrolls V: Skyrim',
 'FIFA 16',
 'Wii Party',
 'Halo 2',
 'Mario Party 8',
 'FIFA Soccer 13',
 'The Sims 3',
 'GoldenEye 007',
 'Mario & Sonic at the Olympic Games',
 'Final Fantasy X',
 'Final Fantasy VIII',
 'Pac-Man',
 'Grand Theft Auto: Liberty City Stories',
 'Super Mario Galaxy 2',
 'Call of Duty: Advanced Warfare',
 'The Legend of Zelda: Ocarina of Time',
 'Call of Duty: World at War',
 'Battlefield 3',
 'The Legend of Zelda: Twilight Princess',
 'Just Dance',
 'Battlefield 3',
 'Need for Speed Underground',
 'Tekken 3',
 'Crash Bandicoot 3: Warped',
 'Super Smash Bros. Melee',
 'Mario Kart 8',
 'Fallout 4',
 'Mario Kart: Double Dash!!',
 'Just Dance 4',
 'FIFA 14',
 'Need for Speed Underground 2',
 "Uncharted 3: Drake's Deception",
 'Gears of War 2',
 'Uncharted 2: Among Thieves',
 'Call of Duty 4: Modern Warfare',
 'Big Brain Academy',
 'Red Dead Redemption',
 'FIFA 15',
 'Donkey Kong Country Returns',
 'The Elder Scrolls V: Skyrim',
 "Assassin's Creed III",
 'Halo: Combat Evolved',
 'Kingdom Hearts',
 'Halo 3: ODST',
 'Red Dead Redemption',
 'Super Mario Sunshine',
 'World of Warcraft',
 'Driver',
 'Kinect Sports',
 'Gears of War 3',
 'Gears of War',
 'Metal Gear Solid 2: Sons of Liberty',
 'Sonic the Hedgehog 2',
 'Metal Gear Solid 4: Guns of the Patriots',
 'Metal Gear Solid',
 'The Last of Us',
 'Final Fantasy XII',
 'LittleBigPlanet',
 'Dragon Quest IX: Sentinels of the Starry Skies',
 'LEGO Star Wars: The Complete Saga',
 'Resident Evil 2',
 'Tekken 2',
 'Cooking Mama',
 'Destiny',
 'Tetris',
 "Assassin's Creed II",
 'Super Smash Bros.',
 "Assassin's Creed",
 'Batman: Arkham City',
 'Forza Motorsport 3',
 'Monster Hunter Freedom Unite',
 'Super Mario Advance',
 'Call of Duty: World at War',
 'Crash Bandicoot: The Wrath of Cortex',
 'Minecraft',
 'Final Fantasy XIII',
 "Assassin's Creed III",
 'Final Fantasy IX',
 'Final Fantasy X-2',
 'Donkey Kong 64',
 "Assassin's Creed II",
 'Professor Layton and the Curious Village',
 'Madden NFL 2004',
 'Dragon Quest VIII: Journey of the Cursed King',
 'Diablo III',
 'New Super Mario Bros. U',
 'FIFA Soccer 13',
 'The Legend of Zelda: Phantom Hourglass',
 'Tomodachi Life',
 'Mario & Sonic at the Olympic Games',
 'Medal of Honor: Rising Sun',
 'Fable III',
 'Call of Duty: Advanced Warfare',
 'Microsoft Flight Simulator',
 'Guitar Hero II',
 'Resident Evil 5',
 'Grand Theft Auto V',
 'Grand Theft Auto: Vice City Stories',
 'FIFA Soccer 11',
 'Resident Evil',
 "Tony Hawk's Pro Skater",
 "Link's Crossbow Training",
 'Guitar Hero III: Legends of Rock',
 'Fallout 3',
 "Uncharted: Drake's Fortune",
 'Madden NFL 06',
 'LEGO Star Wars: The Complete Saga',
 'Diddy Kong Racing',
 'God of War III',
 "Assassin's Creed",
 'FIFA 15',
 'Crash Team Racing',
 'FIFA 17',
 'Batman: Arkham City',
 'Driver 2',
 'The Simpsons: Hit & Run',
 "Tony Hawk's Pro Skater 2",
 'Animal Crossing: City Folk',
 'The Lord of the Rings: The Two Towers',
 'Forza Motorsport 4',
 'Tomb Raider',
 'Guitar Hero III: Legends of Rock',
 'The Legend of Zelda: A Link to the Past',
 'The Legend of Zelda: The Wind Waker',
 'Mario & Sonic at the Olympic Winter Games',
 "Luigi's Mansion: Dark Moon",
 'Splatoon',
 'The Last of Us',
 'Guitar Hero III: Legends of Rock',
 'Madden NFL 2005',
 'Madden NFL 07',
 'Spider-Man: The Movie',
 'Uncharted: The Nathan Drake Collection',
 'Call of Duty: Advanced Warfare',
 'God of War',
 'Nintendo Land',
 "Tony Hawk's Pro Skater 3",
 'Winning Eleven: Pro Evolution Soccer 2007',
 'The Elder Scrolls IV: Oblivion',
 'Need for Speed: Most Wanted',
 'Resistance: Fall of Man',
 'Sonic the Hedgehog',
 'Kingdom Hearts II',
 'FIFA 14',
 'Call of Duty: Advanced Warfare',
 'Fable II',
 'Halo 5: Guardians',
 'Super Mario 3D World',
 'Batman: Arkham Asylum',
 "Assassin's Creed: Revelations",
 'Namco Museum',
 'Metal Gear Solid 3: Snake Eater',
 'Daxter',
 'The Legend of Zelda: Ocarina of Time',
 'FIFA Soccer 06',
 "Uncharted 4: A Thief's End",
 'Gran Turismo 5 Prologue',
 "Assassin's Creed: Revelations",
 'Street Fighter IV',
 'Teenage Mutant Ninja Turtles',
 'Frogger',
 'Madden NFL 2003',
 'Watch Dogs',
 'Half-Life',
 'The Legend of Zelda: Skyward Sword',
 'Carnival Games',
 'Fallout 4',
 'World of Warcraft: The Burning Crusade',
 'Fallout: New Vegas',
 'God of War II',
 'Forza Motorsport 2',
 'World Soccer Winning Eleven 9',
 'Tekken Tag Tournament',
 'Far Cry 4',
 'Star Fox 64',
 'Minecraft',
 'Fallout 3',
 'Professor Layton and the Diabolical Box',
 'Left 4 Dead 2',
 'EA Sports Active',
 "Tony Hawk's Underground",
 "Assassin's Creed IV: Black Flag",
 'Monster Hunter 4 Ultimate',
 'MotorStorm',
 'The Elder Scrolls V: Skyrim',
 'Tekken 5',
 'Sports Champions',
 'NBA 2K16',
 'World Soccer Winning Eleven 8 International',
 'Flash Focus: Vision Training in Minutes a Day',
 "The Legend of Zelda: Link's Awakening",
 "Mario & Luigi: Bowser's Inside Story",
 'Big Brain Academy: Wii Degree',
 'Batman: Arkham Knight',
 'Mario & Sonic at the London 2012 Olympic Games',
 'LEGO Indiana Jones: The Original Adventures',
 'Ratchet & Clank: Size Matters',
 'Just Dance 2014',
 'The Sims: Unleashed',
 'Super Paper Mario',
 "Harry Potter and the Sorcerer's Stone",
 'The Witcher 3: Wild Hunt',
 'Resident Evil 3: Nemesis',
 'Spyro: Year of the Dragon',
 'FIFA Soccer 2005',
 'Battlefield 4',
 'MySims',
 "Tony Hawk's Pro Skater 4",
 'Midnight Club 3: DUB Edition',
 'Banjo-Kazooie',
 'SOCOM: U.S. Navy SEALs',
 'Gran Turismo 6',
 'Jak and Daxter: The Precursor Legacy',
 'Pokemon Snap',
 'FIFA Soccer 10',
 'Pro Evolution Soccer 2008',
 'Call of Duty: Ghosts',
 'Resident Evil 4',
 "Tom Clancy's The Division",
 'Star Wars: Battlefront',
 'The Simpsons: Road Rage',
 'Cooking Mama 2: Dinner With Friends',
 "Luigi's Mansion",
 'Star Wars: Battlefront II',
 'Grand Theft Auto: Liberty City Stories',
 'The Getaway',
 'James Bond 007: Agent Under Fire',
 'Battlefield 4',
 'FIFA Soccer 11',
 'Left 4 Dead',
 'Mario & Sonic at the Olympic Winter Games',
 'Resident Evil 5',
 "Assassin's Creed: Brotherhood",
 'Batman: Arkham Asylum',
 'Clubhouse Games',
 'FIFA Soccer 2004',
 'Battlefield: Bad Company 2',
 'Guitar Hero: On Tour',
 'Far Cry 3',
 'Borderlands',
 'Tekken 4',
 'Battlefield 4',
 'LittleBigPlanet 2',
 'Grand Theft Auto 2',
 'Final Fantasy III',
 'Spider-Man 2',
 'FIFA Soccer 2003',
 'Crash Bash',
 'LEGO Batman: The Videogame',
 'Metal Gear Solid V: The Phantom Pain',
 'The Legend of Zelda: Spirit Tracks',
 "The Legend of Zelda: Majora's Mask",
 'Professor Layton and the Unwound Future',
 "Assassin's Creed IV: Black Flag",
 'Ratchet & Clank',
 'Mario Party 9',
 'Star Wars Episode III: Revenge of the Sith',
 'Max Payne',
 'The Lord of the Rings: The Return of the King',
 "Assassin's Creed Syndicate",
 'Destiny',
 'True Crime: Streets of LA',
 'Wii Music',
 'FIFA 16',
 'L.A. Noire',
 'Madden NFL 16',
 'Killer Instinct',
 'WWF SmackDown! 2: Know Your Role',
 'Crisis Core: Final Fantasy VII',
 'God of War: Chains of Olympus',
 'Dance Central',
 'Enter the Matrix',
 'Super Mario Maker',
 'Fallout: New Vegas',
 'LEGO Batman: The Videogame',
 'Rhythm Heaven',
 'Ace Combat 04: Shattered Skies',
 'Animal Crossing',
 'LEGO Batman: The Videogame',
 'Sonic Rush',
 'Resident Evil 6',
 'Halo: The Master Chief Collection',
 'FIFA Soccer 08',
 'Spider-Man',
 'Personal Trainer: Cooking',
 'The Elder Scrolls IV: Oblivion',
 'Heavy Rain',
 'Mass Effect 2',
 'FIFA 15',
 'Dragon Ball Z: Budokai',
 'Madden NFL 2002',
 'Borderlands 2',
 'The Legend of Zelda: A Link Between Worlds',
 'Mass Effect 3',
 'Kung Fu Panda',
 'Far Cry 3',
 'Saints Row 2',
 'Killzone 2',
 "Tom Clancy's Splinter Cell",
 'WWE SmackDown! Shut Your Mouth',
 'Gears of War: Ultimate Edition',
 'NBA 2K13',
 'Dragon Ball Z: Budokai Tenkaichi 3',
 'World Soccer Winning Eleven 6 International',
 'Devil May Cry',
 'Animal Crossing: Happy Home Designer',
 'Battlefield: Bad Company 2',
 'The Sims 4',
 'Star Wars: The Old Republic',
 'Sonic Heroes',
 'Kirby Super Star Ultra',
 'Hitman 2: Silent Assassin',
 'Street Fighter IV',
 'Wave Race 64',
 'SOCOM II: U.S. Navy SEALs',
 'Pac-Man Collection',
 'Mass Effect',
 'WarioWare: Smooth Moves',
 'Cooking Mama: Cook Off',
 'FIFA 14',
 'Titanfall',
 'Sonic Mega Collection Plus',
 'Sega Superstars Tennis',
 'World Soccer Winning Eleven 7 International',
 'Need for Speed: Most Wanted',
 'Hot Shots Golf 3',
 'Call of Duty: Finest Hour',
 'Syphon Filter',
 'Call of Duty: Ghosts',
 'Madden NFL 13',
 'The Elder Scrolls III: Morrowind',
 'Mortal Kombat',
 "Yoshi's Story",
 'Command & Conquer: Red Alert',
 "Skylanders: Spyro's Adventure",
 'FIFA 16',
 "Assassin's Creed: Brotherhood",
 'BioShock',
 'Madden NFL 10',
 'Medal of Honor',
 'WWE SmackDown! vs. Raw',
 'Metroid Prime',
 'Finding Nemo',
 'Myst',
 'Need for Speed: Hot Pursuit',
 'WWE SmackDown! Here Comes the Pain',
 'Star Wars: The Force Unleashed',
 "Yoshi's Island DS",
 'Killzone 3',
 'WWF SmackDown! Just Bring It',
 'Battlefield 3',
 'NBA Street',
 'Professor Layton and the Last Specter',
 'Monster Hunter Tri',
 'Jak II',
 'Ratchet & Clank: Going Commando',
 'Tekken 6',
 'The Sims',
 'Sonic and the Secret Rings',
 'Saints Row: The Third',
 'Missile Command',
 "Assassin's Creed IV: Black Flag",
 'L.A. Noire',
 'Call of Duty 3',
 'The Legend of Zelda: A Link to the Past',
 'Onimusha: Warlords',
 'Mortal Kombat X',
 'Mario Party',
 'Madden NFL 12',
 'LEGO Star Wars II: The Original Trilogy',
 'Madden NFL 11',
 'Skate 3',
 'Burnout 3: Takedown',
 'Need for Speed: Shift',
 'Final Fantasy XIII-2',
 'Mortal Kombat',
 'Medal of Honor',
 'Fable',
 "Tom Clancy's Splinter Cell",
 'Skylanders Giants',
 'Medal of Honor Heroes',
 'LEGO Star Wars: The Complete Saga',
 'Midnight Club: Street Racing',
 'Halo Wars',
 'God of War Collection',
 'ESPN NFL 2K5',
 'Mario Strikers Charged',
 'Medal of Honor',
 'FIFA Soccer 10',
 'NBA 2K12',
 'Harry Potter and the Chamber of Secrets',
 'FIFA Soccer 09',
 'Ratchet & Clank Future: Tools of Destruction',
 'NBA Live 2005',
 'LittleBigPlanet',
 'Killzone: Shadow Fall',
 'Monster Hunter Freedom 2',
 'Ratchet & Clank: Up Your Arsenal',
 'Art Academy',
 'Dragon Age: Origins',
 'Madden NFL 08',
 'Sonic Adventure 2 Battle',
 'Madden NFL 13',
 'Deca Sports',
 'Madden NFL 09',
 'Crazy Taxi',
 'Perfect Dark',
 'Game Party',
 'Marvel: Ultimate Alliance',
 'Saints Row: The Third',
 'LEGO Harry Potter: Years 1-4',
 'Mortal Kombat: Deadly Alliance',
 'Resistance 2',
 'Pure',
 'NBA 2K13',
 'Rock Band',
 'NBA 2K14',
 'Mario Party 4',
 'uDraw Studio',
 'Midnight Club: Los Angeles',
 'Final Fantasy Tactics',
 'Halo: Combat Evolved Anniversary',
 'Need for Speed Carbon: Own the City',
 "Tom Clancy's Rainbow Six: Vegas 2",
 'Sonic Adventure',
 'Dragon Ball Z: Budokai 2',
 'ATV Offroad Fury',
 'Dino Crisis',
 'Minecraft',
 'Need for Speed: ProStreet',
 'Madden NFL 16',
 'LEGO Indiana Jones: The Original Adventures',
 'Monopoly',
 'Batman: Arkham Origins',
 'Dead Island',
 'Guitar Hero',
 'LEGO Star Wars: The Complete Saga',
 'Kinect: Disneyland Adventures',
 'Bloodborne',
 'NBA 2K15',
 'Madden NFL 11',
 'Yu-Gi-Oh! The Duelists of the Roses',
 'Madden NFL 08',
 'Half-Life 2',
 'The Incredibles',
 "Tony Hawk's Underground 2",
 'Madden NFL 10',
 'Kinect Sports: Season Two',
 'LEGO Harry Potter: Years 1-4',
 'Midnight Club: Los Angeles',
 'The Sims 3',
 "The Legend of Zelda: Majora's Mask 3D",
 'NBA 2K16',
 'Mario Tennis',
 'Grand Theft Auto',
 'James Bond 007: Everything or Nothing',
 'Chrono Trigger',
 'LEGO Marvel Super Heroes',
 'Guild Wars 2',
 'Pokemon Ranger: Shadows of Almia',
 'Dead Island',
 'God of War: Ascension',
 'Need for Speed Underground 2',
 'Pro Evolution Soccer 2010',
 'Just Dance 2015',
 'FIFA Soccer 09',
 'Star Wars: The Force Unleashed',
 'Borderlands 2',
 'Paper Mario: Sticker Star',
 "Sonic's Ultimate Genesis Collection",
 'Super Monkey Ball: Banana Blitz',
 'Kirby: Nightmare in Dream Land',
 'Wario Land 4',
 'Guitar Hero III: Legends of Rock',
 'Call of Duty 3',
 'Resident Evil 4',
 'Minecraft',
 "Onimusha 2: Samurai's Destiny",
 'Paper Mario: The Thousand-Year Door',
 'Madden NFL 12',
 'Monster Hunter Tri',
 'Dissidia: Final Fantasy',
 'Sonic Advance',
 'Spyro: Season of Ice',
 'LEGO Indiana Jones: The Original Adventures',
 'New Super Luigi U',
 'Prince of Persia: The Sands of Time',
 'Scribblenauts',
 'Need for Speed: Hot Pursuit',
 'BioShock 2',
 "Assassin's Creed IV: Black Flag",
 'Rock Band 2',
 'Frogger',
 'Guitar Hero II',
 'Sonic Unleashed',
 'Pro Evolution Soccer 2012',
 'Saints Row',
 'Star Wars: Knights of the Old Republic',
 'Donkey Kong Country',
 'Hitman: Absolution',
 'ATV Offroad Fury 2',
 'Forza Motorsport 5',
 'Madden NFL 25',
 'Pokemon Ranger',
 'Mario & Luigi: Superstar Saga',
 'Final Fantasy XIII',
 'Star Wars: Rogue Squadron',
 'The Sims: House Party',
 'FIFA 15',
 'Call of Duty: Roads to Victory',
 'SimCity 2000',
 'Dance Dance Revolution Extreme',
 'Tetris DS',
 'Final Fantasy Tactics Advance',
 'Final Fantasy III',
 "Kirby's Epic Yarn",
 'Project Gotham Racing',
 'NBA 2K12',
 'Borderlands',
 "Tony Hawk's Pro Skater",
 'Need for Speed: Hot Pursuit 2',
 'Mario Sports Mix',
 'Rock Band',
 'Dynasty Warriors 4',
 'Mortal Kombat',
 'Parasite Eve',
 'Scooby-Doo! Night of 100 Frights',
 'Need for Speed: Most Wanted 5-1-0',
 'Portal 2',
 "Devil May Cry 3: Dante's Awakening",
 'Dead Rising',
 'Finding Nemo',
 'NBA 2K11',
 'The Sims 2: Pets',
 'Metal Gear Solid: Peace Walker',
 'World of Warcraft: Cataclysm',
 'Tetris Worlds',
 'Mario Party 5',
 'Skate 3',
 'Kingdom Hearts: Birth by Sleep',
 'Dark Souls',
 'Need for Speed: ProStreet',
 'The Sims 3',
 "Tom Clancy's Splinter Cell: Conviction",
 'The Incredibles',
 'R4: Ridge Racer Type 4',
 'SoulCalibur II',
 'Mario & Luigi: Dream Team',
 'Need for Speed: ProStreet',
 'Carnival Games',
 'NBA 2K14',
 'Sonic Mega Collection',
 'Diablo III',
 'NBA Jam',
 'Kingdom Hearts 358/2 Days',
 'Dance Central 2',
 'Rayman Raving Rabbids: TV Party',
 "Peter Jackson's King Kong: The Official Game of the Movie",
 'Donkey Kong Country',
 'Need for Speed: The Run',
 'Madden NFL 15',
 'Just Dance 3',
 'NBA Live 2004',
 'Dead Space',
 'Call of Duty 2',
 'Madden NFL 15',
 'Forza Horizon',
 'TouchMaster',
 "Tom Clancy's The Division",
 'LEGO Marvel Super Heroes',
 'Fire Emblem: Awakening',
 'Mortal Kombat vs. DC Universe',
 'Tenchu: Stealth Assassins',
 'Harry Potter and the Chamber of Secrets',
 'Harry Potter and the Chamber of Secrets',
 'SimCity',
 'Battlefield 4',
 'Resident Evil 6',
 'Dragon Age: Inquisition',
 'Sonic Classic Collection',
 'Spyro: Enter the Dragonfly',
 'Call of Duty: World at War',
 'Devil May Cry 2',
 'Burnout Paradise',
 'BioShock Infinite',
 'Hot Shots Golf: Open Tee',
 "Tom Clancy's Rainbow Six: Vegas",
 'Destiny',
 'Crash Nitro Kart',
 'Grand Theft Auto: San Andreas',
 'NBA Street Vol. 2',
 'Def Jam Vendetta',
 'FIFA Soccer 09',
 'Dragon Ball Z: Budokai 3',
 "Tom Clancy's Ghost Recon",
 'X-Men Legends',
 'Batman: Arkham Origins',
 'Mortal Kombat vs. DC Universe',
 'Watch Dogs',
 'Mario Super Sluggers',
 'Need for Speed: Shift',
 'Monopoly',
 'Red Faction',
 "The Sims: Makin' Magic",
 'MX Unleashed',
 'Toy Story Mania!',
 'Mario Party 3',
 'Star Wars: The Force Unleashed',
 'Game Party 2',
 'Destiny: The Taken King',
 'LEGO Star Wars III: The Clone Wars',
 'Star Wars Rogue Leader: Rogue Squadron II',
 'Max Payne 3',
 'Madden NFL 09',
 'Ratchet & Clank Future: A Crack in Time',
 'Mortal Kombat: Deception',
 'High School Musical: Sing It!',
 'Star Fox Adventures',
 'Dynasty Warriors 3',
 'Donkey Kong Country Returns',
 'Madden NFL 06',
 'Shrek 2',
 'The Legend of Dragoon',
 'Turok 2: Seeds of Evil',
 'LittleBigPlanet 3',
 'NBA Live 2002',
 'Chrono Cross',
 'Mario Party: Island Tour',
 'Jak 3',
 'Rayman Raving Rabbids 2',
 'Kingdom Hearts: Chain of Memories',
 "Demon's Souls",
 'NCAA Football 06',
 'Hey You, Pikachu!',
 'World of Warcraft: Mists of Pandaria',
 'Just Cause 3',
 'Secret of Mana',
 'The Orange Box',
 'Kirby: Triple Deluxe',
 'Sonic & Knuckles',
 'Namco Museum',
 'The Sims: Hot Date',
 'Metroid Prime 3: Corruption',
 'Dragon Quest VI: Realms of Revelation',
 'The Evil Within',
 'Crazy Taxi',
 'Virtua Fighter 4',
 'Sly 2: Band of Thieves',
 'Sonic Advance 2',
 'Madden NFL 07',
 'NBA 2K11',
 'Beyond: Two Souls',
 'Kinect Star Wars',
 'Midnight Club II',
 'Dragon Quest Monsters: Joker',
 'The Getaway: Black Monday',
 'Just Cause 2',
 "Dragon's Dogma",
 'The Legend of Zelda: The Wind Waker',
 '50 Cent: Bulletproof',
 'High School Musical: Sing It!',
 'Wii Party U',
 'Madden NFL 25',
 'Final Fantasy II',
 'Kirby 64: The Crystal Shards',
 'Dead or Alive 3',
 'The SpongeBob SquarePants Movie',
 'Golden Sun',
 'Def Jam: Fight for NY',
 "Tom Clancy's Ghost Recon",
 'State of Emergency',
 'BioShock Infinite',
 'Hitman: Absolution',
 'The Urbz: Sims in the City',
 'FIFA Soccer 08',
 'Star Wars: Starfighter',
 'Kingdom Hearts',
 'Star Wars: Battlefront',
 'Crackdown',
 "Disney's Aladdin",
 'Cooking Mama 3: Shop & Chop',
 'Xenosaga Episode I: Der Wille zur Macht',
 'Portal 2',
 'The Beatles: Rock Band',
 'Forza Motorsport 6',
 'Sonic Colors',
 'Diablo III',
 'Uncharted: Golden Abyss',
 'Destiny',
 'SSX Tricky',
 'Overwatch',
 "Harry Potter and the Sorcerer's Stone",
 'Disney Infinity',
 'Crash Bandicoot: The Huge Adventure',
 'Dishonored',
 'The Order: 1886',
 'The Elder Scrolls Online',
 'Call of Duty: Modern Warfare 3',
 'Madden NFL 2005',
 'The Sims 3: Late Night Expansion Pack',
 'Toy Story 2: Buzz Lightyear to the Rescue!',
 'Deal or No Deal',
 'Ace Combat 5: The Unsung War',
 'Need for Speed Underground',
 'Tetris Worlds',
 'The Crew',
 'FIFA Soccer 10',
 'We Ski',
 'Personal Trainer: Math',
 'NCAA Football 07',
 'SOCOM 3: U.S. Navy SEALs',
 'NBA 2K15',
 'Saints Row 2',
 'Saints Row IV',
 'Dragon Age: Origins',
 'FIFA 16',
 "Harry Potter and the Sorcerer's Stone",
 'Dragon Ball Z: The Legacy of Goku',
 "Sid Meier's Civilization V",
 'Resident Evil 4',
 'Star Wars Battlefront: Renegade Squadron',
 'World Championship Poker: Featuring Howard Lederer - All In',
 'LEGO Batman 2: DC Super Heroes',
 'The Sims: Superstar',
 'Star Wars The Clone Wars: Lightsaber Duels',
 'MySims',
 'Metroid Fusion',
 'Shaun White Snowboarding: Road Trip',
 'SSX 3',
 'Big Beach Sports',
 'Madden NFL 2001',
 'Fight Night Round 3',
 'Knack',
 'Star Wars: Battlefront II',
 "Tony Hawk's Pro Skater 3",
 'Monsters, Inc.',
 'Spy Hunter',
 'NCAA Football 2004',
 'SpongeBob SquarePants: Battle for Bikini Bottom',
 'Dying Light',
 'Heavenly Sword',
 'SSX',
 'Max Payne 3',
 'NBA Ballers',
 'Need for Speed Carbon',
 'NBA Live 2003',
 'Dragon Ball Z: Budokai Tenkaichi',
 'Ms. Pac-Man',
 'Mario Party 6',
 'Go Vacation',
 'Army of Two',

Not necessary, but seeing which titles didn't have a match between the datasets

In [9]:
non_matches = reviews.loc[~reviews['name'].isin(sales['Name']), 'name'].unique().tolist()
missing_count = len(non_matches)
print(missing_count)
non_matches

7143

['Red Dead Redemption 2',
 'The Legend of Zelda: Breath of the Wild',
 'Super Mario Odyssey',
 'Grand Theft Auto Double Pack',
 "Baldur's Gate II: Shadows of Amn",
 "The Legend of Zelda Collector's Edition",
 'Persona 5 Royal',
 'The Last of Us Remastered',
 'The Legend of Zelda: Ocarina of Time 3D',
 'Celeste',
 "Sid Meier's Civilization II",
 'Super Mario Advance 4: Super Mario Bros. 3',
 'Grim Fandango',
 "Tom Clancy's Splinter Cell Chaos Theory",
 'The Last of Us Part II',
 "Tom Clancy's Splinter Cell Pandora Tomorrow",
 'Divinity: Original Sin II - Definitive Edition',
 'Pac-Man Championship Edition DX',
 'Hades',
 'Half-Life: Alyx',
 'Divinity: Original Sin II',
 'Ori and the Will of the Wisps',
 'Starcraft II: Wings of Liberty',
 'Undertale',
 'Persona 4 Golden',
 'Quake III Arena',
 'Mario Kart Super Circuit',
 'NBA 2K1',
 'Super Smash Bros. Ultimate',
 'Wipeout XL',
 'INSIDE',
 'Flipnote Studio',
 'Forza Horizon 4',
 "Sid Meier's Gettysburg!",
 'Super Street Fighter IV',
 'What Remains of Edith Finch',
 'Team Fortress 2',
 'System Shock 2',
 'Super Mario World: Super Mario Advance 2',
 'Okami HD',
 'Thief: The Dark Project',
 'The Walking Dead: A Telltale Games Series',
 'Unreal Tournament (1999)',
 "Sid Meier's Alpha Centauri",
 'Galactic Civilizations II: Twilight of the Arnor',
 'Super Smash Bros. for Wii U',
 'PaRappa the Rapper',
 'Mario Kart 8 Deluxe',
 'Out of the Park Baseball 17',
 'The Witcher 3: Wild Hunt - Blood and Wine',
 'Medal of Honor: Allied Assault',
 'Myth: The Fallen Lords',
 'Metroid Prime Trilogy',
 "F1 Challenge '99-'02",
 "Baldur's Gate",
 'FreeSpace 2',
 'Dragon Quest XI S: Echoes of an Elusive Age - Definitive Edition',
 'Sekiro: Shadows Die Twice',
 'Resident Evil 4: Wii Edition',
 'Peggle',
 'The Legend of Zelda: Ocarina of Time / Master Quest',
 'Sonic Mania Plus',
 'Dead Cells',
 'Kentucky Route Zero - Act III',
 'Final Fantasy XIV: Shadowbringers',
 'DOA2: Hardcore',
 "Yoshi's Island: Super Mario Advance 3",
 'Star Wars Jedi Knight: Dark Forces II',
 'Galactic Civilizations II: Dark Avatar',
 'Crusader Kings III',
 'Fez',
 "No One Lives Forever 2: A Spy in H.A.R.M.'s Way",
 'F1 2020',
 'Mark of the Ninja',
 'Disco Elysium',
 'SteamWorld Heist: Ultimate Edition',
 'Spelunky 2',
 'NieR: Automata - Game of the YoRHa Edition',
 'Shovel Knight: Treasure Trove',
 'flower',
 'Call of Duty',
 'Project Gotham Racing 2',
 'Animal Crossing: New Horizons',
 'Diablo III: Ultimate Evil Edition',
 'FIFA Soccer 12',
 'Marvel vs. Capcom 2',
 'Trials Evolution',
 'Grand Theft Auto IV: The Lost and Damned',
 'Monster Hunter: World - Iceborne',
 'Spelunky',
 'Tennis 2K2',
 'The Legend of Zelda: The Wind Waker HD',
 'Portal',
 'Tetris Effect',
 'Dance Dance Revolution',
 'NieR: Automata - Become as Gods Edition',
 'Bastion',
 'Monster Hunter: World',
 "Stephen's Sausage Roll",
 'Velocity 2X',
 'Portal: Still Alive',
 'Half-Life 2: Episode Two',
 "The Chronicles of Riddick: Escape From Butcher Bay - Developer's Cut",
 'Hollow Knight',
 "Sid Meier's Civilization III",
 'LIMBO',
 'Ori and the Blind Forest: Definitive Edition',
 'Super Meat Boy',
 'Geometry Wars: Retro Evolved 2',
 'Mario Kart 8 DLC Pack 2',
 'Flight Simulator 2002',
 'Dota 2',
 'Tales From The Borderlands: Episode 5 - The Vault of the Traveler',
 'Pushmo',
 'The Witcher 3: Wild Hunt - Hearts of Stone',
 'Metal Gear Solid HD Collection',
 'Freedom Force',
 'Into the Breach',
 'GTR 2',
 'Yakuza 0',
 'Astro Bot: Rescue Mission',
 'Bayonetta + Bayonetta 2',
 'Kentucky Route Zero - Act IV',
 'Guacamelee! Super Turbo Championship Edition',
 'Rayman 2 Revolution',
 'Beetle Adventure Racing',
 'Wipeout HD Fury',
 'Xenoblade Chronicles: Definitive Edition',
 'Skylanders Swap Force',
 'Sacrifice',
 'Samba de Amigo',
 'Wipeout 3',
 'Rez HD',
 'F1 2019',
 'Rez Infinite',
 'Rocksmith 2014 Edition',
 'Fallout',
 'Worldwide Soccer Manager 2005',
 'Yakuza: Like a Dragon',
 'There is no game : Wrong dimension',
 'Axiom Verge',
 'Titanfall 2',
 'F1 2017',
 'Devil May Cry 5',
 '3D Gunstar Heroes',
 'NASCAR Racing 2002 Season',
 'Grand Theft Auto IV: The Ballad of Gay Tony',
 'Combat Mission: Barbarossa to Berlin',
 'Homeworld: Cataclysm',
 'Cave Story',
 'Dark Souls II: Scholar of the First Sin',
 'The Walking Dead: Episode 5 - No Time Left',
 'Slay the Spire',
 '3D Streets of Rage II',
 'Out of the Park Baseball 15',
 'Fire Emblem: Three Houses',
 'Final Fantasy XIV: Stormblood',
 'Stardew Valley',
 'NASCAR Racing 4',
 'Duke Nukem 3D',
 'Nuclear Throne',
 'Lone Echo',
 'Apex Legends',
 'NASCAR Racing 2003 Season',
 'Descent 3',
 'The Curse of Monkey Island',
 'Dark Souls: Artorias of the Abyss',
 "Tony Hawk's Pro Skater 1 + 2",
 'Dreams',
 'Einhander',
 'The Chronicles of Riddick: Escape From Butcher Bay',
 'Return of the Obra Dinn',
 'Lumines',
 "Tom Clancy's Splinter Cell Double Agent",
 'Battlefield 1',
 'WarioWare, Inc.: Mega Microgame$!',
 'Colors! 3D',
 'Horizon Zero Dawn',
 'Injustice 2',
 'Minecraft: PlayStation 4 Edition',
 "Asgard's Wrath",
 'Wipeout Pure',
 'XCOM 2: War of the Chosen',
 'DUSK',
 'Medieval: Total War',
 'Shadow Complex',
 'N++',
 'Brothers in Arms: Road to Hill 30',
 "Deus Ex: Human Revolution - Director's Cut",
 'Crusader Kings II: The Old Gods',
 'Pinball FX 2: Marvel Pinball - Avengers Chronicles',
 'Medal of Honor Frontline',
 'Superbike 2001',
 'Wolfenstein II: The New Colossus',
 'Divinity: Original Sin Enhanced Edition',
 'The Binding of Isaac: Rebirth',
 'Kerbal Space Program',
 'Tribes 2',
 'Age of Empires II: The Conquerors Expansion',
 'NieR: Automata',
 'Dishonored 2',
 'Rise of the Tomb Raider: 20 Year Celebration',
 'Hyper Light Drifter',
 'The Banner Saga 3',
 "Tom Clancy's Rainbow Six Vegas",
 'Super Street Fighter II Turbo HD Remix',
 'Starcraft',
 'The Last of Us: Left Behind',
 'DOOM Eternal',
 'Star Wars Pinball: Balance of the Force',
 'The Secret of Monkey Island: Special Edition',
 'Project Gotham Racing 3',
 'The World Ends with You',
 'Torchlight II',
 'Injustice 2: Legendary Edition',
 'Cuphead',
 'Minecraft: Xbox One Edition',
 'XCOM: Enemy Within',
 'Myth II: Soulblighter',
 'Fire Emblem Fates: Special Edition',
 'Pinball FX 2',
 'The Elder Scrolls III: Morrowind Game of the Year Edition',
 'Halo: The Master Chief Collection - Halo 3',
 'Pokemon Y',
 'Return to Castle Wolfenstein',
 'Ori and the Blind Forest',
 'Shogo: Mobile Armor Division',
 'Thirty Flights of Loving',
 'Hearthstone: Heroes of Warcraft',
 'Unity of Command II',
 'The Walking Dead: Episode 3 - Long Road Ahead',
 'Super Mario Maker 2',
 'Tekken: Dark Resurrection',
 'The Stanley Parable',
 'Guacamelee! Gold Edition',
 'Fire Emblem Fates: Revelation',
 "Sid Meier's Civilization VI",
 'Starcraft II: Legacy of the Void',
 'Downwell',
 'Owlboy',
 'Diablo III: Eternal Collection',
 'Rise of Nations: Thrones & Patriots',
 'A Short Hike',
 'Battlefield: Bad Company 2 Vietnam',
 'EVE Online: Special Edition',
 'SteamWorld Dig 2',
 'Armadillo Run',
 'Pillars of Eternity II: Deadfire',
 'Art of Balance',
 'Keep Talking and Nobody Explodes',
 'Joe Danger: Special Edition',
 'Cave Story +',
 'Dark Age of Camelot',
 "Baldur's Gate II: Throne of Bhaal",
 'The Talos Principle: Deluxe Edition',
 'Night in the Woods',
 'Pistol Whip',
 'Nex Machina: Death Machine',
 'Nioh',
 'Kentucky Route Zero: TV Edition',
 "Hellblade: Senua's Sacrifice",
 'DOOM 3',
 'Subnautica',
 'Frostpunk: Console Edition',
 'Middle-earth: Shadow of Mordor',
 'Bloodborne: The Old Hunters',
 'The Witness',
 'DOOM',
 'Rallisport Challenge 2',
 "Oddworld: Abe's Oddysee - New 'n' Tasty",
 'Final Fantasy VII Remake',
 "Monkey Island 2 Special Edition: LeChuck's Revenge",
 'Red Dead Redemption: Undead Nightmare Pack',
 'Pokemon White Version',
 'Pokemon X',
 'RimWorld',
 'Europa Universalis II',
 'Metropolis Street Racer',
 'Power Stone 2',
 'Street Fighter V: Arcade Edition',
 'Guacamelee!',
 'Astral Chain',
 'GRID (2008)',
 'Critter Crunch',
 'Crypt of the NecroDancer',
 'La-Mulana',
 'Pokemon Sun',
 'Dragon Ball FighterZ',
 'The Walking Dead: Season Two Episode 5 - No Going Back',
 'MechWarrior 4: Vengeance',
 'Thief II: The Metal Age',
 'Half-Life 2: Episode One',
 'Devil May Cry 3: Special Edition',
 'Guacamelee! 2',
 'Mass Effect 2: Lair of the Shadow Broker',
 'Enter the Gungeon',
 'The Swapper',
 'Baba Is You',
 'Pokemon SoulSilver Version',
 'Super Mega Baseball 3',
 "Assassin's Creed Odyssey",
 'Year Walk',
 'Mario Kart 8 DLC Pack 1',
 "Marvel's Spider-Man",
 'Pokemon Moon',
 'TowerFall Ascension',
 'Battlefield 3: Armored Kill',
 'Rallisport Challenge',
 'Bangai-O',
 'Icewind Dale',
 'Fire Emblem Fates: Conquest',
 'Skylanders SuperChargers',
 '3D Sonic the Hedgehog 2',
 'Monster Boy and the Cursed Kingdom',
 'Kohan: Immortal Sovereigns',
 'Hotline Miami',
 'SteamWorld Heist',
 'Raw Data',
 'Pokemon HeartGold Version',
 'Diablo III: Reaper of Souls',
 'Bionic Commando Rearmed',
 'Zero Escape: The Nonary Games',
 'Shogun: Total War Warlord Edition',
 'Serious Sam: The First Encounter',
 'Grand Prix 3',
 'Pokemon Black Version',
 'Call of Duty: United Offensive',
 'Odin Sphere Leifthrasir',
 'Wipeout HD',
 'Huntdown',
 'Legends of Runeterra',
 'Unavowed',
 '3D Out Run',
 'Katamari Damacy REROLL',
 'Destiny 2',
 'Bit.Trip Presents...Runner2: Future Legend of Rhythm Alien',
 'Sin & Punishment: Star Successor',
 'Forza Horizon 3: Blizzard Mountain',
 'Out of the Park Baseball 4',
 'Velocity',
 'Pinball FX 2: Star Wars Pinball',
 'Europa Universalis IV',
 'Sunless Skies',
 'Total War: WARHAMMER II',
 'Zeus: Master of Olympus',
 'Dark Souls II: Crown of the Ivory King',
 'Velocity Ultra',
 'Forza Horizon 3: Hot Wheels',
 'Hex: Shards of Fate',
 'PixelJunk Shooter',
 'Warhammer 40,000: Dawn of War - Dark Crusade',
 'West of Loathing',
 'Iconoclasts',
 'LostWinds: Winter of the Melodias',
 'Thumper',
 'Gone Home',
 'Pac-Man Championship Edition DX +',
 'Bomberman Blast',
 'The Elder Scrolls IV: Shivering Isles',
 'Tales from the Borderlands: A Telltale Game Series',
 'Startopia',
 'Enemy Engaged: RAH-66 Comanche Versus Ka-52 Hokum',
 'Fallout 2',
 'Out of the Park Baseball 14',
 'Borderlands: The Secret Armory of General Knoxx',
 'Astebreed',
 'Ground Control',
 'Killer Instinct Season 3',
 'Pillars of Eternity: Complete Edition',
 'The Messenger',
 'Kentucky Route Zero',
 'Need for Speed: Most Wanted U',
 'DmC: Devil May Cry Definitive Edition',
 'Mercenaries',
 'EverQuest: Omens of War',
 'Steel Beasts',
 'Test Drive V-Rally',
 'Total Annihilation',
 'Transistor',
 "Sid Meier's Civilization IV: Beyond the Sword",
 'Dragon Quest Builders 2',
 'Sky Force Reloaded',
 'Steins;Gate Elite',
 'Freedom Force vs The 3rd Reich',
 'Fluidity',
 'Death Stranding',
 'Thimbleweed Park',
 'Picross 3D: Round 2',
 'Tribes: Ascend',
 "Borderlands 2: Tiny Tina's Assault on Dragon Keep",
 'Minecraft: Switch Edition',
 'Gears of War 4',
 'Ni no Kuni: Wrath of the White Witch Remastered',
 'Valfaris',
 'Guilty Gear Xrd -REVELATOR-',
 'Pinball FX 2: Marvel Pinball',
 'Trials HD',
 'Panzer Corps 2',
 'Her Story',
 'Starcraft II: Heart of the Swarm',
 'Resident Evil 7: biohazard',
 'Dungeon Siege',
 'Star Wars: Knights of the Old Republic II: The Sith Lords',
 'Crashmo',
 'Guitar Hero World Tour',
 'Street Fighter III: Third Strike Online Edition',
 'Final Fantasy XII: The Zodiac Age',
 'Star Wars Pinball',
 'CrossCode',
 'Galactic Civilizations II: Dread Lords',
 'Medal of Honor Underground',
 'Need for Speed: High Stakes',
 'Destiny 2: Forsaken',
 'Streets of Rage 4',
 '13 Sentinels: Aegis Rim',
 "Fell Seal: Arbiter's Mark",
 'AI: The Somnium Files',
 'Geometry Wars: Retro Evolved',
 'F1 2016',
 'Minecraft: PlayStation 3 Edition',
 'Sonic Mania',
 'Joe Danger',
 "Age of Wonders II: The Wizard's Throne",
 'Links 2001',
 'EverQuest: The Ruins of Kunark',
 'Full Throttle',
 'The Lord of the Rings Online: Shadows of Angmar',
 'Mortal Kombat 11',
 'Pony Island',
 'Tomb Raider: Definitive Edition',
 'MLB The Show 19',
 'Tales From Space: Mutant Blobs Attack',
 'Desperados III',
 "PlayerUnknown's Battlegrounds",
 'The Elder Scrolls IV - Knights of the Nine',
 'Crypt of the NecroDancer: Nintendo Switch Edition',
 'Observer',
 'ZEN Pinball 2',
 "Command & Conquer: Red Alert 2 - Yuri's Revenge",
 'Europa Universalis',
 'Escape from Monkey Island',
 'Beat Saber',
 'Warframe',
 "Luigi's Mansion 3",
 'Shatter',
 'Final Fantasy XIV Online: A Realm Reborn',
 'Battlefield 3: Back to Karkand',
 'Dragon Quest XI: Echoes of an Elusive Age',
 'Dying Light: The Following',
 'Heroes of the Storm',
 'DiRT 4',
 'Code:Realize - Guardian of Rebirth',
 'Civilization III: Conquests',
 'Path of Exile',
 'Guilty Gear Xrd: Rev 2',
 'OlliOlli2: Welcome to Olliwood',
 'Assault Android Cactus+',
 'Forza Motorsport 7',
 'Football Manager 2019',
 'Gunman Clive HD Collection',
 'Persona 4 Arena',
 'BlazBlue: Central Fiction - Special Edition',
 'Day of the Tentacle Remastered',
 'Xenoblade Chronicles 3D',
 'Fire Emblem Fates: Birthright',
 'Mini Metro',
 'Dark Souls Remastered',
 'Resogun: Heroes',
 'Tetris Party',
 'Allegiance',
 'Cadence of Hyrule: Crypt of the NecroDancer Featuring The Legend of Zelda',
 'Monster Hunter Generations',
 "Shantae: Risky's Revenge",
 'Project Gotham Racing 4',
 'Metroid Prime: Hunters',
 'Metroid: Samus Returns',
 'Heroes of Hammerwatch - Ultimate Edition',
 'The Wolf Among Us: Episode 1 - Faith',
 'Deep Rock Galactic',
 'Falcon 4.0',
 'Legend of Grimrock II',
 'NHL 20',
 'Thronebreaker: The Witcher Tales',
 "Sam & Max Episode 205: What's New, Beelzebub?",
 'Hearthstone: Heroes of Warcraft - Whispers of the Old Gods',
 'The Outer Worlds',
 'Firewatch',
 'Wasteland 3',
 'City of Heroes',
 'Mass Effect 3: Special Edition',
 'Castle Crashers',
 'Pokemon Pearl Version',
 'Blaster Master Zero II',
 'Lara Croft and the Guardian of Light',
 "Clive Barker's Undying",
 'EverQuest',
 'Trials Evolution: Origin of Pain',
 'Monster Train',
 'Bravely Default',
 'Risk of Rain 2',
 'Call of Duty: Black Ops 4',
 'Paradigm',
 'Bug Fables: The Everlasting Sapling',
 'Battlerite',
 'Final Fantasy XV: Windows Edition',
 "Nioh: Bloodshed's End",
 'Out of the Park Baseball 13',
 'Wizardry 8',
 'Aliens Versus Predator 2',
 'Operation Flashpoint: Cold War Crisis',
 'Tropico',
 'MotoGP 3: Ultimate Racing Technology',
 'NASCAR SimRacing',
 'Devotion',
 'The Binding of Isaac: Afterbirth',
 'Amnesia: The Dark Descent',
 'Chaos Reborn',
 "Assassin's Creed Origins",
 "Assassin's Creed Valhalla",
 'GTR: FIA GT Racing Game',
 'The Witcher 3: Wild Hunt - Complete Edition',
 'Rogue Legacy',
 'Control',
 'Dust: An Elysian Tail',
 "Marvel's Spider-Man: Miles Morales",
 'Dark Souls: Prepare to Die Edition',
 'The Binding of Isaac: Afterbirth +',
 'Shadow Tactics: Blades of the Shogun',
 'Super Smash Bros. for Nintendo 3DS',
 'Medieval II: Total War Kingdoms',
 'VA-11 Hall-A: Cyberpunk Bartender Action',
 'DJMax Respect',
 'Resogun: Defenders',
 'The Legend of Zelda: Four Swords Anniversary Edition',
 "Maboshi's Arcade",
 'Peggle Deluxe',
 'Monopoly Tycoon',
 'Sam & Max Episode 204: Chariots of the Dogs',
 'Ys VIII: Lacrimosa of DANA',
 'Nioh 2',
 'Frozen Synapse',
 'Bayonetta & Vanquish',
 'Zenzizenzic',
 'NBA Jam: On Fire Edition',
 'Galactic Civilizations III: Crusade',
 'Robo Recall',
 'Super Stardust HD',
 'Sine Mora',
 'Two Point Hospital',
 'AudioSurf',
 'Super Mario 64 DS',
 'MLB The Show 17',
 'BattleBlock Theater',
 'Star Wars: Knights of the Old Republic II - The Sith Lords',
 'AMID EVIL',
 'Batman: The Enemy Within - Episode 5: Same Stitch',
 'Assault Android Cactus',
 'Persona 4 Arena Ultimax',
 'Full Metal Furies',
 'Super Mega Baseball',
 'DDRMAX: Dance Dance Revolution',
 'F355 Challenge',
 'The Elder Scrolls III: Bloodmoon',
 'Pokemon Diamond Version',
 'Yakuza Kiwami 2',
 'Manifold Garden',
 "Sam & Max: The Devil's Playhouse - Episode 2: The Tomb of Sammun-Mak",
 'The Wolf Among Us: Episode 5 - Cry Wolf',
 "Crash Bandicoot 4: It's About Time",
 'Age of Wonders: Planetfall',
 'System Shock: Enhanced Edition',
 'EverQuest: Gates of Discord',
 'Wipeout: Omega Collection',
 'Tangle Tower',
 'Mortal Kombat XL',
 'Lego Star Wars II: The Original Trilogy',
 "Sid Meier's Civilization V: Brave New World",
 'Geometry Wars 3: Dimensions',
 'MLB The Show 16',
 'Valkyria Chronicles 4',
 'Darkest Dungeon',
 'Mutant Mudds Collection',
 'NeuroVoider',
 'Total War: Three Kingdoms',
 'The Last Door: Season 2',
 'Brothers in Arms: Earned in Blood',
 'Serious Sam: The Second Encounter',
 "American McGee's Alice",
 'Batman: Arkham City - Armored Edition',
 'Chime Sharp',
 'Trials Evolution: Gold Edition',
 'Moss',
 'The Walking Dead: The Telltale Definitive Series',
 'Warhammer 40,000: Dawn of War - Winter Assault',
 'Outer Wilds',
 'Trials Rising',
 'Starcraft Remastered',
 'NBA 2K18',
 'Planescape: Torment - Enhanced Edition',
 'Pyre',
 'inFamous',
 'Papers, Please',
 'Radiant Historia: Perfect Chronology',
 'Mario + Rabbids: Kingdom Battle',
 'Disgaea 4 Complete+',
 '428: Shibuya Scramble',
 'Enter The Gungeon',
 'Gone Home: Console Edition',
 'FIFA 07 Soccer',
 'Anarchy Online: Shadowlands',
 'Dark Age of Camelot: Shrouded Isles',
 'Obsidian',
 'DiRT Rally 2.0',
 'The Walking Dead: Episode 2 - Starved for Help',
 'Bomberman Live',
 'Ni no Kuni II: Revenant Kingdom',
 'Project CARS 2',
 'Statik',
 'Shantae: Half-Genie Hero - Ultimate Edition',
 'Valkyria Chronicles Remastered',
 'Crash Team Racing: Nitro-Fueled',
 'F1 2018',
 'Kingdom Hearts HD I.5 + II.5 Remix',
 'Virtua Tennis: World Tour',
 'Lonely Mountains: Downhill',
 'Neverwinter Nights: Hordes of the Underdark',
 'Command & Conquer: Generals',
 "Sid Meier's SimGolf",
 'Quake III Revolution',
 'Street Fighter III: Double Impact',
 'Pikmin 3 Deluxe',
 'SpaceChem',
 'Freedom Planet',
 'Pokemon Ultra Sun',
 'South Park: The Fractured But Whole',
 'Blast Off',
 'If Found...',
 'PlanetSide 2',
 'Planet Coaster',
 'Shovel Knight: Specter of Torment',
 'Guilty Gear Xrd -SIGN-',
 "'Splosion Man",
 'TxK',
 'Pro Evolution Soccer 2009',
 'Beyond Good & Evil HD',
 'Rakuen',
 'BioShock: The Collection',
 'BlazBlue: Central Fiction',
 'Sound Shapes',
 'Gears 5',
 'Hearthstone: Heroes of Warcraft - Goblins Vs. Gnomes',
 'WHAT THE GOLF?',
 'Salt and Sanctuary',
 'Space Rangers 2: Rise of the Dominators',
 'Tales From The Borderlands: Episode 1 - Zer0 Sum',
 'Sprint Vector',
 'Black Mesa',
 '80 DAYS',
 'Toki Tori 2 +',
 'Heroes of Might and Magic IV',
 'Shogun: Total War',
 'Outland',
 'Mega Man X Legacy Collection',
 'Rayman Legends: Definitive Edition',
 'Shin Megami Tensei: Devil Survivor 2 Record Breaker',
 'Mass Effect 3: Citadel',
 'Horace',
 'Super Street Fighter IV: Arcade Edition',
 'ZEN Pinball 2: South Park: Super-Sweet Pinball',
 "Trine 2: Director's Cut",
 'Guild Wars Factions',
 'Gorogoa',
 'Battle Chasers: Nightwar',
 'SoulCalibur VI',
 '80 Days (2015)',
 'Unity of Command',
 'Kingdom: Two Crowns',
 'The Missing: JJ Macfield and the Island of Memories',
 'Hearthstone: Heroes of Warcraft - The Grand Tournament',
 'Eliza',
 'Metro Redux',
 'Horizon Zero Dawn: Complete Edition',
 "Mario & Luigi: Bowser's Inside Story + Bowser Jr.'s Journey",
 'Total War: WARHAMMER II - Rise of the Tomb Kings',
 'Grim Fandango Remastered',
 'Need for Speed: Most Wanted - A Criterion Game',
 'Frozen Synapse Prime',
 'Wargroove',
 'Stacking',
 'Battlefield 1943',
 'Lovers in a Dangerous Spacetime',
 'Dishonored: Death of the Outsider',
 'The Banner Saga 2',
 'Europa Universalis IV: Wealth of Nations',
 'BioShock Infinite: Burial at Sea - Episode Two',
 'Disciples II: Dark Prophecy',
 'Frostpunk',
 'Football Manager 2020',
 'Polybius',
 'Crysis Warhead',
 'Uncharted: The Lost Legacy',
 'Bloodstained: Ritual of the Night',
 'Worms 2: Armageddon',
 'Hitman - Episode 2: Sapienza',
 'ZEN Pinball 2: Aliens Vs. Pinball',
 'Bit.Trip Complete',
 'Splashdown',
 'WipeOut 64',
 'Magic: The Gathering Arena',
 "Lone Survivor: The Director's Cut",
 'Lair of the Clockwork God',

Finding the names of all platforms used in both datasets to create a roadmap for conversion to 1 style

In [10]:
r_platforms = reviews["platform"].unique().tolist()
s_platforms = sales["Platform"].unique().tolist()
print(r_platforms)
print(s_platforms)

['Nintendo64', 'PlayStation', 'PlayStation3', 'Dreamcast', 'Xbox360', 'Wii', 'XboxOne', 'Switch', 'PlayStation2', 'PlayStation4', 'GameCube', 'Xbox', 'PC', 'WiiU', 'GameBoyAdvance', '3DS', 'DS', 'PlayStationVita', 'PSP', 'XboxSeriesX', 'PlayStation5', 'Stadia']
['Wii', 'NES', 'GB', 'DS', 'X360', 'PS3', 'PS2', 'SNES', 'GBA', '3DS', 'PS4', 'N64', 'PS', 'XB', 'PC', '2600', 'PSP', 'XOne', 'GC', 'WiiU', 'GEN', 'DC', 'PSV', 'SAT', 'SCD', 'WS', 'NG', 'TG16', '3DO', 'GG', 'PCFX']

Converting the release date column from the video game reviews csv to just be by year for convenience and removing the previous release date column

In [11]:
reviews["Year"] = pd.to_datetime(reviews["r-date"]).dt.year
reviews

,name,platform,r-date,score,user score,developer,genre,players,critics,users,Year
0,The Legend of Zelda: Ocarina of Time,Nintendo64,"November 23, 1998",99,9.1,Nintendo,"Action Adventure,Fantasy",1 Player,22,5749,1998
1,Tony Hawk's Pro Skater 2,PlayStation,"September 20, 2000",98,7.4,NeversoftEntertainment,"Sports,Alternative,Skateboarding",1-2,19,647,2000
2,Grand Theft Auto IV,PlayStation3,"April 29, 2008",98,7.6,RockstarNorth,"Action Adventure,Modern,Modern,Open-World",1 Player,64,3806,2008
3,SoulCalibur,Dreamcast,"September 8, 1999",98,8.5,Namco,"Action,Fighting,3D",1-2,24,324,1999
4,Grand Theft Auto IV,Xbox360,"April 29, 2008",98,7.9,RockstarNorth,"Action Adventure,Modern,Modern,Open-World",1 Player,86,3364,2008
...,...,...,...,...,...,...,...,...,...,...,...
17939,Vroom in the Night Sky,Switch,"April 5, 2017",17,3.1,Poisoft,"Sports,Individual,Biking",No Online Multiplayer,15,105,2017
17940,Leisure Suit Larry: Box Office Bust,PlayStation3,"May 5, 2009",17,1.9,Team17,"Action Adventure,Adventure,Third-Person,Open-W...",No Online Multiplayer,11,45,2009
17941,Yaris,Xbox360,"October 10, 2007",17,4.3,BackboneEntertainment,"Driving,Racing,Arcade,Arcade,Automobile",2 Online,7,129,2007
17942,Ride to Hell: Retribution,PC,"June 24, 2013",16,1.3,"Eutechnyx,DeepSilver","Driving,Modern,Racing,Motorcycle,Motocross,Mod...",No info,9,581,2013
17943,Family Party: 30 Great Games Obstacle Arcade,WiiU,"December 4, 2012",11,2.0,"ArtCo.,Ltd.","Miscellaneous,Party,Party,Party / Minigame",No Online Multiplayer,8,151,2012

Creating and applying the platform map to the video game reviews dataset for easy merging and matching

In [12]:
platform_map = {'Nintendo64': 'N64', 'PlayStation' : 'PS', 'PlayStation3': 'PS3', 'Dreamcast': 'DC', 'Xbox360': 'X360', 'Wii': 'Wii', 'XboxOne': 'XOne', 'PlayStation2': 'PS2', 'PlayStation4': 'PS4', 'GameCube': 'GC', 'PC': 'PC', 'WiiU': 'WiiU', 'GameBoyAdvance': 'GBA', '3DS': '3DS', 'DS': 'DS', 'PlayStationVita': 'PSV'}
reviews["platform"] = reviews["platform"].map(platform_map)
reviews.dropna(subset=["platform"], inplace=True)
reviews.reset_index(drop=True, inplace=True)
reviews

,name,platform,r-date,score,user score,developer,genre,players,critics,users,Year
0,The Legend of Zelda: Ocarina of Time,N64,"November 23, 1998",99,9.1,Nintendo,"Action Adventure,Fantasy",1 Player,22,5749,1998
1,Tony Hawk's Pro Skater 2,PS,"September 20, 2000",98,7.4,NeversoftEntertainment,"Sports,Alternative,Skateboarding",1-2,19,647,2000
2,Grand Theft Auto IV,PS3,"April 29, 2008",98,7.6,RockstarNorth,"Action Adventure,Modern,Modern,Open-World",1 Player,64,3806,2008
3,SoulCalibur,DC,"September 8, 1999",98,8.5,Namco,"Action,Fighting,3D",1-2,24,324,1999
4,Grand Theft Auto IV,X360,"April 29, 2008",98,7.9,RockstarNorth,"Action Adventure,Modern,Modern,Open-World",1 Player,86,3364,2008
...,...,...,...,...,...,...,...,...,...,...,...
15502,Double Dragon II: Wander of the Dragons,X360,"April 5, 2013",17,1.5,"GravityCorporation,Gravity","Action,Beat-'Em-Up,Beat-'Em-Up,2D",No info,19,58,2013
15503,Leisure Suit Larry: Box Office Bust,PS3,"May 5, 2009",17,1.9,Team17,"Action Adventure,Adventure,Third-Person,Open-W...",No Online Multiplayer,11,45,2009
15504,Yaris,X360,"October 10, 2007",17,4.3,BackboneEntertainment,"Driving,Racing,Arcade,Arcade,Automobile",2 Online,7,129,2007
15505,Ride to Hell: Retribution,PC,"June 24, 2013",16,1.3,"Eutechnyx,DeepSilver","Driving,Modern,Racing,Motorcycle,Motocross,Mod...",No info,9,581,2013
15506,Family Party: 30 Great Games Obstacle Arcade,WiiU,"December 4, 2012",11,2.0,"ArtCo.,Ltd.","Miscellaneous,Party,Party,Party / Minigame",No Online Multiplayer,8,151,2012

Dropping duplicates in both datasets that may have been created/already exist and resetting the index for merging

In [13]:
reviews.drop_duplicates(subset=["name", "platform", "Year"], inplace=True)
reviews.reset_index(drop=True, inplace=True)
sales.drop_duplicates(subset=["Name", "Platform", "Year"], inplace=True)
sales.reset_index(drop=True, inplace=True)

Merging the two datasets with an inner join by name(game title), platform, and year(release year)\
Did a 1:1 validation to ensure all entries are correctly merged\
Dropping unnecessary columns for analysis later

In [14]:
df_merged = pd.merge(sales, reviews, left_on=["Name", "Platform", "Year"], right_on=["name", "platform", "Year"], validate="1:1", how="inner")
df_merged.drop(columns=["name", "platform", 'r-date', 'genre', 'Rank'], inplace=True)
df_merged.head()

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,score,user score,developer,players,critics,users
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,76,8.0,Nintendo,No Online Multiplayer,51,429
1,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,82,8.4,Nintendo,Up to 12,73,982
2,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,80,8.1,Nintendo,1-4,73,266
3,New Super Mario Bros.,DS,2006.0,Platform,Nintendo,11.38,9.23,6.50,2.90,30.01,89,8.5,Nintendo,No Online Multiplayer,65,639
4,New Super Mario Bros. Wii,Wii,2009.0,Platform,Nintendo,14.59,7.06,4.70,2.26,28.62,87,8.3,Nintendo,No Online Multiplayer,80,767

## Verify the merge

Went through a 1:1 validate to make sure that reviews entries were matched up by at most 1 of the sales entries
See code above 


!Disclaimer! There is potential for more accurate matching if you go through fuzzy matching and check all the games to ensure they are referencing the correct iteration, platform, etc. Requires lots of manual checking to be sure!!! I did not do this, however given the assignment I feel that this was sufficient for accuracy's sake.

## Export your merged data set

Exported merged dataset to be used for analysis

In [ ]:
df_merged.to_csv("Merged Video Game Sales and Reviews.csv")